"""Phase 14AK -- injection-based probability calibration diagnostic.

The public reliability figure is a Monte Carlo self-consistency check. This
script adds a truth-labelled GeDR3mock diagnostic using the shipped
injection-recovery table: bin mock stars by predicted P(Vgrf<25) and compare
with the fraction whose injected true speed is actually below 25 km/s.

The mock has a balanced injected velocity prior, so this is not a population
prior calibration for the Gaia catalogue. It is a transparent check of whether
the probability score is monotonic and conservative in a controlled mock.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BUNDLE = Path(__file__).resolve().parents[1]
REPO = BUNDLE.parents[1]
INP = BUNDLE / "phase14" / "injection_recovery" / "wp7_recovery_per_star_s500.csv"
OUT = BUNDLE / "phase14" / "injection_recovery"
TAB_DIRS = [REPO / "release" / "tables" / "v15", BUNDLE / "tables" / "v15"]
FIG_DIRS = [REPO / "release" / "figures", BUNDLE / "figures"]

BINS = [0.0, 0.10, 0.30, 0.50, 0.70, 0.84, 0.95, 1.0000001]
LABELS = ["0--0.10", "0.10--0.30", "0.30--0.50", "0.50--0.70",
          "0.70--0.84", "0.84--0.95", "0.95--1.00"]


def clean_label(s: pd.Series) -> pd.Series:
    return (s.astype(str)
             .str.replace("b'", "", regex=False)
             .str.replace("'", "", regex=False)
             .str.strip())


def wilson(k: int, n: int, z: float = 1.0) -> tuple[float, float]:
    if n == 0:
        return np.nan, np.nan
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return float((c - h) / d), float((c + h) / d)


def main() -> int:
    df = pd.read_csv(INP)
    df["vgrf_bin"] = clean_label(df["vgrf_bin"])
    df["tier"] = clean_label(df["tier"])
    df["true_slow"] = df["vgrf_bin"].eq("0-25")
    df["pipeline_input"] = (
        df["rvs_available_draw"].astype(bool)
        & df["parallax_quality_pass"].astype(bool)
        & df["rvs_quality_pass"].astype(bool)
    )
    work = df[df["pipeline_input"]].copy()
    work["p_bin"] = pd.cut(
        work["P_vgrf_below_25"],
        bins=BINS,
        labels=LABELS,
        include_lowest=True,
        right=False,
    )

    rows = []
    for label in LABELS:
        sub = work[work["p_bin"].eq(label)]
        n = int(len(sub))
        k = int(sub["true_slow"].sum())
        lo, hi = wilson(k, n)
        rows.append({
            "p_bin": label,
            "n": n,
            "predicted_mean": float(sub["P_vgrf_below_25"].mean()) if n else np.nan,
            "true_slow_fraction": float(k / n) if n else np.nan,
            "true_slow_fraction_lo": lo,
            "true_slow_fraction_hi": hi,
            "residual_true_minus_predicted": float(k / n - sub["P_vgrf_below_25"].mean()) if n else np.nan,
        })

    out = pd.DataFrame(rows)
    brier = float(np.mean((work["P_vgrf_below_25"].to_numpy(float)
                           - work["true_slow"].to_numpy(float)) ** 2))
    tier_rows = {}
    for name, cut in [("A", 0.95), ("A+B", 0.84), ("A+B+C", 0.50)]:
        sub = work[work["P_vgrf_below_25"] > cut]
        tier_rows[name] = {
            "n": int(len(sub)),
            "true_slow_fraction": float(sub["true_slow"].mean()) if len(sub) else np.nan,
            "mean_probability": float(sub["P_vgrf_below_25"].mean()) if len(sub) else np.nan,
        }

    OUT.mkdir(parents=True, exist_ok=True)
    out.to_csv(OUT / "wp7_probability_calibration_bins.csv", index=False)
    payload = {
        "input": str(INP.relative_to(BUNDLE)),
        "mock_prior_note": (
            "Controlled GeDR3mock injections are balanced across true Vgrf bins; "
            "this is a truth-labelled score diagnostic, not a population-prior "
            "calibration for the observed catalogue."
        ),
        "n_pipeline_input": int(len(work)),
        "brier_score_pipeline_input": brier,
        "tier_thresholds": tier_rows,
        "bins": rows,
    }
    (OUT / "wp7_probability_calibration_summary.json").write_text(json.dumps(payload, indent=2))
    write_table(out, brier)
    write_figure(out)
    print(json.dumps(payload, indent=2))
    return 0


def write_table(out: pd.DataFrame, brier: float) -> None:
    lines = [
        r"% Auto-generated by scripts/phase14ak_probability_calibration.py",
        r"\begin{deluxetable}{lrrrr}",
        r"\tablecaption{Truth-labelled GeDR3mock probability-score diagnostic for"
        r" pipeline-input mock stars. The mock is balanced across injected true"
        r" $\vgrf$ bins, so this table checks monotonic score behaviour rather than"
        r" population-prior calibration. The Brier score over the pipeline-input mock"
        rf" is {brier:.3f}.\label{{tab:probability_calibration}}}}",
        r"\tablehead{\colhead{$P(\vgrf<25)$ bin} & \colhead{$N$} &"
        r" \colhead{$\langle P\rangle$} & \colhead{true sub-25 frac.} &"
        r" \colhead{true$-\langle P\rangle$}}",
        r"\startdata",
    ]
    for _, r in out.iterrows():
        lines.append(
            f"{r['p_bin']} & {int(r['n'])} & {r['predicted_mean']:.3f} & "
            f"{r['true_slow_fraction']:.3f} & {r['residual_true_minus_predicted']:+.3f} \\\\"
        )
    lines += [r"\enddata", r"\end{deluxetable}"]
    text = "\n".join(lines) + "\n"
    for d in TAB_DIRS:
        d.mkdir(parents=True, exist_ok=True)
        (d / "tab_probability_calibration.tex").write_text(text)


def write_figure(out: pd.DataFrame) -> None:
    x = out["predicted_mean"].to_numpy(float)
    y = out["true_slow_fraction"].to_numpy(float)
    lo = out["true_slow_fraction_lo"].to_numpy(float)
    hi = out["true_slow_fraction_hi"].to_numpy(float)
    n = out["n"].to_numpy(int)

    fig, ax = plt.subplots(figsize=(4.6, 3.6))
    ax.plot([0, 1], [0, 1], color="0.4", lw=0.8, ls="--")
    ax.errorbar(x, y, yerr=[y - lo, hi - y], fmt="o", ms=4.5,
                color="#1f77b4", ecolor="#6baed6", capsize=2)
    for xi, yi, ni in zip(x, y, n):
        ax.annotate(str(ni), (xi, yi), xytext=(3, 3), textcoords="offset points", fontsize=6)
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)
    ax.set_xlabel(r"Mean predicted $P(V_{\rm grf}<25)$")
    ax.set_ylabel("Injected true sub-25 fraction")
    ax.set_title("GeDR3mock truth-labelled score diagnostic")
    fig.tight_layout()
    for d in FIG_DIRS:
        d.mkdir(parents=True, exist_ok=True)
        fig.savefig(d / "fig_probability_calibration.pdf", bbox_inches="tight", dpi=250)
    plt.close(fig)


if __name__ == "__main__":
    raise SystemExit(main())
