# Milky Way potential from Hunter+ 2024 with added rotation
[Potential]
file=MWPotentialHunter24_full.ini
# The line below specifies both the orientation of the bar and the its pattern speed as follows:
# the first pair of numbers [0,phi0] sets the angle of CCW rotation of the bar (in radians)
# at present time (t=0);
# the second pair [1,phi0+Omega*1] sets its angle at time t=1.
# Given that there are only two numbers, the angle is linearly interpolated between them,
# and always extrapolated linearly beyond the endpoints of the interval, corresponding to
# a constant pattern speed Omega (here it is negative, i.e. CW rotation).
# Units are: length=1 kpc, velocity=1 km/s (hence pattern speed is km/s/kpc);
# there are no potential parameters with the dimension of mass, so the mass unit is unspecified.
rotation=[[0,-0.44],[1,-37.94]]
